version: '3.0'

services:
  api:
    build: ./api
    hostname: api
    ports: 
      - 7500:7500
    networks: 
      - bot-network
    entrypoint: ['node', 'start.js']
    environment:
     - SWAGGER_BASE_PATH
  articulate:
    build: ./articulate
    hostname: articulate
    ports: 
      - 3000:3000
    networks: 
      - bot-network
    environment:
      - API_URL=http://${host}:7500
  rasa:
    hostname: rasa
    build: ./rasa
    image: rasa-base:latest
    networks: 
      - bot-network
    volumes: 
      - ./local-storage/rasa/nlu-model:/app/models
      - ./local-storage/rasa/nlu-vector:/app/vectors
      - ./local-storage/rasa/rasa-config.yml:/app/config.yml
      - ./local-storage/rasa/logs:/app/logs
    environment:
      - RASA_LOG_LEVEL='DEBUG'
  rasa-build:
    hostname: rasa-build
    build: ./rasa-build
    image: rasa-build:latest
    volumes: 
      - ./local-storage/rasa/nlu-model:/app/models
      - ./local-storage/rasa/nlu-vector:/app/vectors
    networks: 
      - bot-network
    command: ./prepare-models.sh --language-package=fr --download-vectors=true --generate-models=true 
  duckling:
    hostname: duckling
    build: ./duckling
    ports: 
      - 8000:8000
    networks: 
      - bot-network
  redis:
    hostname: redis
    image: redis:alpine
    ports: 
      - 6379:6379
    networks: 
      - bot-network
    command: redis-server --appendonly yes
    volumes: 
      - ./local-storage/redis-data:/data

networks: {bot-network: {}}
